const moment = require("moment");

exports.seed = function (knex) {
    // Deletes ALL existing entries
    return knex("rates")
        .del()
        .then(function () {
            // Inserts seed entries
            return knex("rates").insert([
                {
                    id: 1,
                    day_type: "regular",
                    holiday_type: "non-holiday",
                    time_type: "regular",
                    abbreviation: "regular",
                    rate: 1.0,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 2,
                    day_type: "regular",
                    holiday_type: "special holiday",
                    time_type: "regular",
                    abbreviation: "SH",
                    rate: 1.3,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 3,
                    day_type: "regular",
                    holiday_type: "regular holiday",
                    time_type: "regular",
                    abbreviation: "RH",
                    rate: 2.0,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 4,
                    day_type: "regular",
                    holiday_type: "regular holiday, regular holiday",
                    time_type: "regular",
                    abbreviation: "2RH",
                    rate: 3.0,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 5,
                    day_type: "regular",
                    holiday_type: "non-holiday",
                    time_type: "night",
                    abbreviation: "NT",
                    rate: 1.1,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 6,
                    day_type: "regular",
                    holiday_type: "special holiday",
                    time_type: "night",
                    abbreviation: "SH+NT",
                    rate: 1.43,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 7,
                    day_type: "regular",
                    holiday_type: "regular holiday",
                    time_type: "night",
                    abbreviation: "RH+NT",
                    rate: 2.2,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 8,
                    day_type: "regular",
                    holiday_type: "regular holiday, regular holiday",
                    time_type: "night",
                    abbreviation: "2RH+NT",
                    rate: 3.3,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 9,
                    day_type: "regular",
                    holiday_type: "non-holiday",
                    time_type: "overtime",
                    abbreviation: "OT",
                    rate: 1.25,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 10,
                    day_type: "regular",
                    holiday_type: "special holiday",
                    time_type: "overtime",
                    abbreviation: "SH+OT",
                    rate: 1.69,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 11,
                    day_type: "regular",
                    holiday_type: "regular holiday",
                    time_type: "overtime",
                    abbreviation: "RH+OT",
                    rate: 2.6,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 12,
                    day_type: "regular",
                    holiday_type: "regular holiday, regular holiday",
                    time_type: "overtime",
                    abbreviation: "2RH+OT",
                    rate: 3.9,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 13,
                    day_type: "regular",
                    holiday_type: "non-holiday",
                    time_type: "night, overtime",
                    abbreviation: "NT+OT",
                    rate: 1.375,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 14,
                    day_type: "regular",
                    holiday_type: "special holiday",
                    time_type: "night, overtime",
                    abbreviation: "SH+NT+OT",
                    rate: 1.859,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 15,
                    day_type: "regular",
                    holiday_type: "regular holiday",
                    time_type: "night, overtime",
                    abbreviation: "RH+NT+OT",
                    rate: 2.86,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 16,
                    day_type: "regular",
                    holiday_type: "regular holiday, regular holiday",
                    time_type: "night, overtime",
                    abbreviation: "2RH+NT+OT",
                    rate: 4.29,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 17,
                    day_type: "rest day",
                    holiday_type: "non-holiday",
                    time_type: "regular",
                    abbreviation: "RD",
                    rate: 1.3,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 18,
                    day_type: "rest day",
                    holiday_type: "special holiday",
                    time_type: "regular",
                    abbreviation: "RD+SH",
                    rate: 1.5,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 19,
                    day_type: "rest day",
                    holiday_type: "regular holiday",
                    time_type: "regular",
                    abbreviation: "RD+RH",
                    rate: 2.6,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 20,
                    day_type: "regular",
                    holiday_type: "regular holiday, regular holiday",
                    time_type: "regular",
                    abbreviation: "RD+2RH",
                    rate: 3.9,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 21,
                    day_type: "rest day",
                    holiday_type: "non-holiday",
                    time_type: "night",
                    abbreviation: "RD+NT",
                    rate: 1.43,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 22,
                    day_type: "rest day",
                    holiday_type: "special holiday",
                    time_type: "night",
                    abbreviation: "RD+SH+NT",
                    rate: 1.65,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 23,
                    day_type: "rest day",
                    holiday_type: "regular holiday",
                    time_type: "night",
                    abbreviation: "RD+RH+NT",
                    rate: 2.86,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 24,
                    day_type: "rest day",
                    holiday_type: "regular holiday, regular holiday",
                    time_type: "night",
                    abbreviation: "RD+2RH+NT",
                    rate: 4.29,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 25,
                    day_type: "rest day",
                    holiday_type: "non-holiday",
                    time_type: "overtime",
                    abbreviation: "RD+OT",
                    rate: 1.69,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 26,
                    day_type: "rest day",
                    holiday_type: "special holiday",
                    time_type: "overtime",
                    abbreviation: "RD+SH+OT",
                    rate: 1.95,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 27,
                    day_type: "rest day",
                    holiday_type: "regular holiday",
                    time_type: "overtime",
                    abbreviation: "RD+RH+OT",
                    rate: 3.38,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 28,
                    day_type: "rest day",
                    holiday_type: "regular holiday, regular holiday",
                    time_type: "overtime",
                    abbreviation: "RD+2RH+OT",
                    rate: 5.07,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 29,
                    day_type: "rest day",
                    holiday_type: "non-holiday",
                    time_type: "night, overtime",
                    abbreviation: "RD+NT+OT",
                    rate: 1.859,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 30,
                    day_type: "rest day",
                    holiday_type: "special holiday",
                    time_type: "night, overtime",
                    abbreviation: "RD+SH+NT+OT",
                    rate: 2.145,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 31,
                    day_type: "rest day",
                    holiday_type: "regular holiday",
                    time_type: "night, overtime",
                    abbreviation: "RD+RH+NT+OT",
                    rate: 3.718,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
                {
                    id: 32,
                    day_type: "rest day",
                    holiday_type: "regular holiday, regular holiday",
                    time_type: "night, overtime",
                    abbreviation: "RD+2RH+NT+OT",
                    rate: 5.577,
                    created_by: "system",
                    created_on: moment().format("YYYY-MM-DD HH:mm:ss"),
                },
            ]);
        });
};
